name: build-test

on: [ push ]

jobs:
  integration-testing:
    name: Integration testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages
        run: npm install
      - name: Run Jest
        run: npx test